set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

set bs=2
set tabstop=8 softtabstop=8 shiftwidth=4 smarttab expandtab
set t_Co=256
set number ruler cursorline relativenumber
set mouse=vn
set scrolloff=5
set completeopt+=noselect,menuone
autocmd bufreadpre *.md setlocal textwidth=80

noremap <C-f> :Files  <CR>
map <C-l> :Lines <CR>
noremap <C-b> :Buffers <CR>

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-surround'
Plugin 'airblade/vim-gitgutter'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'tpope/vim-obsession'
Plugin 'tpope/vim-fugitive'

set background=dark
colorscheme retrobox
call vundle#end()
filetype plugin indent on
syntax enable
