noremap <C-f> :Files  <CR>
map <C-l> :Lines <CR>
noremap <C-b> :Buffers <CR>

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-surround'
Plugin 'airblade/vim-gitgutter'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'tpope/vim-obsession'
Plugin 'tpope/vim-fugitive'

set background=dark
colorscheme retrobox
call vundle#end()
filetype plugin indent on
syntax enable
