- name: System Configuration
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
  tasks:
    - name: Startup
      debug:
        msg: Starting system setup
    - name: Package Management 
      include_role:
        name: "src/packages"
    - name: Configs Setup
      include_role:
        name: "src/config"
    - name: System setup
      include_role:
        name: "src/system"
