[colors.normal]
black = "#282828"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#d4be98"
yellow = "#e78a4e"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "alacritty"

[font]
size = 12.0

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Super"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Super"
