- name: Setup Repositories
  block:
  - name: Setup Free RPM Repository
    ansible.builtin.shell: 'dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm'
  - name: Setup Non-Free RPM Repository
    ansible.builtin.shell: 'dnf install -y   https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
  - name: Setup K8S Repository
    ansible.builtin.copy:
      src: kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo
      owner: root
      group: root
      mode: '0644'

- name: Setup Flathub
  ansible.builtin.shell: 'flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo'

- name: "Install Package Group: {{ group }}"
  ansible.builtin.include_tasks: package.yaml
  loop: "{{ package_groups }}"
  loop_control:
    loop_var: "group"

