- name: Setup Flathub
  ansible.builtin.shell: 'flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo'

- name: "Install Package Group: {{ group }}"
  ansible.builtin.include_tasks: package.yaml
  loop: "{{ package_groups }}"
  loop_control:
    loop_var: "group"

- name: Install UV packages - todoman
  ansible.builtin.shell: 'uv tool install todoman'
- name: Install UV packages - ty
  ansible.builtin.shell: 'uv tool install ty'
- name: Install UV packages - khard
  ansible.builtin.shell: 'uv tool install khard'
