#! /bin/sh
~/.screenlayout/work.sh
export GPG_TTY=$(tty)
nitrogen --restore
~/.config/polybar/forest/launch.sh 2> /dev/null
#picom --config  ~/.config/picom/picom.conf --experimental-backends  2> /dev/null &
#picom --config  ~/.config/picom/picom.conf --experimental-backends  2> /dev/null &
spgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr

dunst &
xfce4-power-manager &
pipewire &
pipewire-pulse &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color '#0C1115'
bspc config focused_border_color '#ebdbb2'
