#! /bin/sh


~/.screenlayout/work.sh
nitrogen --restore
~/.config/polybar/forest/launch.sh 2> /dev/null
#picom --config  ~/.config/picom/picom.conf --experimental-backends  2> /dev/null &
picom --config  ~/.config/picom/picom.conf --experimental-backends  2> /dev/null &
pgrep -x sxhkd > /dev/null || sxhkd &

dunst &
xfce4-power-manager &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config active_border_color '#0C1115'
bspc config focused_border_color '#ebdbb2'
