- name: Configure Terminal
  block:
    - name: Setup Alacritty
      ansible.builtin.copy:
        src: alacritty/alacritty.toml
        dest: "~/.config/alacritty/"
        backup: yes

    - name: Setup Shell
      ansible.builtin.copy:
        src: shell/bashrc
        dest: "~/.bashrc"
        backup: yes

    - name: Setup shell user source directory
      ansible.builtin.copy:
        src: shell/bashrc.d/
        dest: "~/.bashrc.d"

    - name: Setup tmux
      ansible.builtin.copy:
        src: tmux/.tmux.conf
        dest: "~/.tmux.conf"
        backup: yes


- name: Setup Editor
  block:
    - name: Setup vimrc
      ansible.builtin.copy:
        src: neovim/vimrc
        dest: "~/.vimrc"
        backup: yes

    - name: Ensure nvim dir exists
      ansible.builtin.file:
        path: "~/.config/nvim/"
        state: directory

    - name: Setup init.vim
      ansible.builtin.copy:
        src: neovim/init.vim
        dest: "~/.config/nvim/init.vim"
        backup: yes

    - name: Setup neovim lua configs
      ansible.builtin.copy:
        src: neovim/lua/
        dest: "~/.config/nvim/lua"
        backup: yes

    - name: Setup neovim lsp
      ansible.builtin.copy:
        src: neovim/lsp/
        dest: "~/.config/nvim/lsp"
        backup: yes

    - name: Setup Vundle
      ansible.builtin.shell: 'git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim && vim +PluginInstall +qall'
      ignore_errors: true

- name: Configure Email
  block:
    - name: Setup msmtprc
      ansible.builtin.template:
        src: neomutt/msmtprc.j2
        dest: "~/.msmtprc"
        backup: yes

    - name: Setup mbsyncrc
      ansible.builtin.template:
        src: neomutt/mbsyncrc.j2
        dest: "~/.mbsyncrc"
        backup: yes

    - name: Ensure mutt dir exists
      ansible.builtin.file:
        path: "~/.mutt"
        state: directory

    - name: Setup Neomutt
      ansible.builtin.template:
        src: neomutt/neomuttrc.j2
        dest: "~/.mutt/neomuttrc"
        backup: yes

    - name: Setup Neomutt - mutt_generate_attachment_commands
      ansible.builtin.copy:
        src: neomutt/mutt_generate_attachment_commands
        dest: "~/.local/bin/"
        backup: yes

    - name: Setup Neomutt - Mailcap
      ansible.builtin.copy:
        src: neomutt/mailcap
        dest: "~/.mutt/"
        backup: yes


- name: Configure Misc
  block:
    - name: Ensure misc dirs exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.vdirsyncer"
        - "~/.config/todoman"
        - "~/.config/khal"
        - "~/.config/khard"
    - name: Setup vdirsyncer
      ansible.builtin.copy:
        src: caldav/vdirsyncer
        dest: "~/.vdirsyncer/config"
    - name: Setup todoman
      ansible.builtin.copy:
        src: caldav/todoman.py
        dest: "~/.config/todoman/config.py"
    - name: Setup khal
      ansible.builtin.copy:
        src: caldav/khal
        dest: "~/.config/khal/config"
    - name: Setup khard
      ansible.builtin.copy:
        src: caldav/khard.conf
        dest: "~/.config/khard/khard.conf"
    - name: vdirsyncer - discover
      ansible.builtin.shell: "yes | vdirsyncer discover"
    - name: vdirsyncer - sync 
      ansible.builtin.shell: "yes | vdirsyncer sync"
    - name: vdirsyncer - metasync
      ansible.builtin.shell: "yes | vdirsyncer metasync"
    - name: Setup Wallpapers
      ansible.builtin.copy:
        src: wallpapers
        dest: "~/.config/wallpapers"
        backup: yes
