- name: Configure Terminal
  block:
    - name: Setup Alacritty
      ansible.builtin.copy:
        src: alacritty/alacritty.toml
        dest: "/home/{{ username }}/.config/alacritty/"
        backup: yes

    - name: Setup Shell
      ansible.builtin.copy:
        src: shell/bashrc
        dest: "/home/{{ username }}/.bashrc"
        backup: yes

    - name: Setup shell user source directory
      ansible.builtin.copy:
        src: shell/bashrc.d/
        dest: "/home/{{ username }}/.bashrc.d"
        backup: yes

    - name: Setup Starship
      ansible.builtin.copy:
        src: starship/starship.toml
        dest: "/home/{{ username }}/.config/starship.toml"
        backup: yes

    - name: Setup tmux
      ansible.builtin.copy:
        src: tmux/.tmux.conf
        dest: "/home/{{ username }}"
        backup: yes


- name: Setup Editor
  block:
    - name: Setup vimrc
      ansible.builtin.copy:
        src: neovim/vimrc
        dest: "/home/{{ username }}/.vimrc"
        backup: yes

    - name: Setup init.vim
      ansible.builtin.copy:
        src: neovim/init.vim
        dest: "/home/{{ username }}/.config/nvim/init.vim"
        backup: yes

    - name: Setup neovim lua configs
      ansible.builtin.copy:
        src: neovim/lua/
        dest: "/home/{{ username }}/.config/nvim/lua"
        backup: yes
    - name: Setup neovim lsp
      ansible.builtin.copy:
        src: neovim/lsp/
        dest: "/home/{{ username }}/.config/nvim/lsp"
        backup: yes

    - name: Setup Vundle
      ansible.builtin.shell: 'git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim && vim +PluginInstall +qall'
      ignore_errors: true

- name: Configure Email
  block:
    - name: Setup msmtprc
      ansible.builtin.template:
        src: neomutt/msmtprc.j2
        dest: "/home/{{ username }}/.msmtprc"
        backup: yes

    - name: Setup mbsyncrc
      ansible.builtin.template:
        src: neomutt/mbsyncrc.j2
        dest: "/home/{{ username }}/.mbsyncrc"
        backup: yes

    - name: Setup Neomutt
      ansible.builtin.template:
        src: neomutt/neomuttrc.j2
        dest: "/home/{{ username }}/.mutt/neomuttrc"
        backup: yes

    - name: Setup Neomutt - mutt_generate_attachment_commands
      ansible.builtin.copy:
        src: neomutt/mutt_generate_attachment_commands
        dest: "/home/{{ username }}/.local/bin/"
        backup: yes

    - name: Setup Neomutt - Mailcap
      ansible.builtin.copy:
        src: neomutt/mailcap
        dest: "/home/{{ username }}/.mutt/"
        backup: yes


- name: Configure Misc
  block:
    - name: Setup Wallpapers
      ansible.builtin.copy:
        src: wallpapers
        dest: "/home/{{ username }}/.config/wallpapers"
        backup: yes
